package com.dhl.ocnt.model;

import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;

/**
 * Movement generated by hbm2java
 */
public class Movement_backup1 extends Page<Movement>{

	private String movementId;
	private String oriFacId;
	private String destFacId;
	private Timestamp mvmtSchdDepartureDt;
	private boolean hasCutoff;
	private String firstSecDesig;
	private String lastSecDesig;
	private String carrierCode;
	private int networkRouteNum;
	private Timestamp mvmtEtaDt;
	private String transportationModeCode;
	private String vehicleId;
	private String mvmtStatusCode;
	private String oriSvaCode;
	private String destSvaCode;
	private String createdBy;	
	private Timestamp createdDt;
	private String updatedBy;
	private Timestamp updatedDt;
	private String fleetType;
	private String mawbId;
	private String docTypeCd;
	private String sysGuid;
	private Timestamp closeDt;
	private Timestamp departDt;
	private List<HandlingUnitInMovement> huInMvmt;
	private Timestamp cutOffTime;
	
	public List<HandlingUnitInMovement> getHuInMvmt() {
		if(huInMvmt == null)
		{
			huInMvmt =  new ArrayList<HandlingUnitInMovement>();
		}
		
		return this.huInMvmt;
	}

	public void setHuInMvmt(ArrayList<HandlingUnitInMovement> huInMvmt) {
		this.huInMvmt = huInMvmt;
	}

	public Timestamp getDepartDt() {
		return departDt;
	}

	public void setDepartDt(Timestamp departDt) {
		this.departDt = departDt;
	}

	public Timestamp getCloseDt() {
		return closeDt;
	}

	public void setCloseDt(Timestamp closeDt) {
		this.closeDt = closeDt;
	}

	public Movement_backup1() {
	}

	public Movement_backup1(String movementId) {
		this.movementId = movementId;
	}

	public Movement_backup1(String movementId, String oriFacId, String destFacId,
			Timestamp mvmtSchdDepartureDt, String firstSecDesig,
			String lastSecDesig, String carrierCode, int networkRouteNum,
			Timestamp mvmtEtaDt, String transportationModeCode,
			String vehicleId, String mvmtStatusCode, String destSvaCode,
			String createdBy, Timestamp createdDt, String updatedBy,
			Timestamp updatedDt) {
		this.movementId = movementId;
		this.oriFacId = oriFacId;
		this.destFacId = destFacId;
		this.mvmtSchdDepartureDt = mvmtSchdDepartureDt;
		this.firstSecDesig = firstSecDesig;
		this.lastSecDesig = lastSecDesig;
		this.carrierCode = carrierCode;
		this.networkRouteNum = networkRouteNum;
		this.mvmtEtaDt = mvmtEtaDt;
		this.transportationModeCode = transportationModeCode;
		this.vehicleId = vehicleId;
		this.mvmtStatusCode = mvmtStatusCode;
		this.destSvaCode = destSvaCode;
		this.createdBy = createdBy;
		this.createdDt = createdDt;
		this.updatedBy = updatedBy;
		this.updatedDt = updatedDt;
	}

	public String getMovementId() {
		return this.movementId;
	}

	public void setMovementId(String movementId) {
		this.movementId = movementId;
	}

	public String getOriFacId() {
		return this.oriFacId;
	}

	public void setOriFacId(String oriFacId) {
		this.oriFacId = oriFacId;
	}

	public String getDestFacId() {
		return this.destFacId;
	}

	public void setDestFacId(String destFacId) {
		this.destFacId = destFacId;
	}

	public Timestamp getMvmtSchdDepartureDt() {
		return this.mvmtSchdDepartureDt;
	}

	public void setMvmtSchdDepartureDt(Timestamp mvmtSchdDepartureDt) {
		this.mvmtSchdDepartureDt = mvmtSchdDepartureDt;
	}

	public String getFirstSecDesig() {
		return this.firstSecDesig;
	}

	public void setFirstSecDesig(String firstSecDesig) {
		this.firstSecDesig = firstSecDesig;
	}

	public String getLastSecDesig() {
		return this.lastSecDesig;
	}

	public void setLastSecDesig(String lastSecDesig) {
		this.lastSecDesig = lastSecDesig;
	}

	public String getCarrierCode() {
		return this.carrierCode;
	}

	public void setCarrierCode(String carrierCode) {
		this.carrierCode = carrierCode;
	}

	public int getNetworkRouteNum() {
		return this.networkRouteNum;
	}

	public void setNetworkRouteNum(int networkRouteNum) {
		this.networkRouteNum = networkRouteNum;
	}

	public Timestamp getMvmtEtaDt() {
		return this.mvmtEtaDt;
	}

	public void setMvmtEtaDt(Timestamp mvmtEtaDt) {
		this.mvmtEtaDt = mvmtEtaDt;
	}

	public String getTransportationModeCode() {
		return this.transportationModeCode;
	}

	public void setTransportationModeCode(String transportationModeCode) {
		this.transportationModeCode = transportationModeCode;
	}

	public String getVehicleId() {
		return this.vehicleId;
	}

	public void setVehicleId(String vehicleId) {
		this.vehicleId = vehicleId;
	}

	public String getMvmtStatusCode() {
		return this.mvmtStatusCode;
	}

	public void setMvmtStatusCode(String mvmtStatusCode) {
		this.mvmtStatusCode = mvmtStatusCode;
	}
	
	public String getOriSvaCode() {
		return this.oriSvaCode;
	}

	public void setOriSvaCode(String oriSvaCode) {
		this.oriSvaCode = oriSvaCode;
	}

	public String getDestSvaCode() {
		return this.destSvaCode;
	}

	public void setDestSvaCode(String destSvaCode) {
		this.destSvaCode = destSvaCode;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Timestamp getCreatedDt() {
		return this.createdDt;
	}

	public void setCreatedDt(Timestamp createdDt) {
		this.createdDt = createdDt;
	}

	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Timestamp getUpdatedDt() {
		return this.updatedDt;
	}

	public void setUpdatedDt(Timestamp updatedDt) {
		this.updatedDt = updatedDt;
	}

	public String getFleetType() {
		return fleetType;
	}

	public void setFleetType(String fleetType) {
		this.fleetType = fleetType;
	}

	public String getMawbId() {
		return mawbId;
	}

	public void setMawbId(String mawbId) {
		this.mawbId = mawbId;
	}

	public String getDocTypeCd() {
		return docTypeCd;
	}

	public void setDocTypeCd(String docTypeCd) {
		this.docTypeCd = docTypeCd;
	}

	public String getSysGuid() {
		return sysGuid;
	}

	public void setSysGuid(String sysGuid) {
		this.sysGuid = sysGuid;
	}	

	public boolean isHasCutoff() {
		return hasCutoff;
	}

	public void setHasCutoff(boolean hasCutoff) {
		this.hasCutoff = hasCutoff;
	}	

	public Timestamp getCutOffTime() {
		return cutOffTime;
	}

	public void setCutOffTime(Timestamp cutOffTime) {
		this.cutOffTime = cutOffTime;
	}

	@Override
	public String toString() {
		return "Movement [movementId=" + movementId + ", oriFacId=" + oriFacId
				+ ", destFacId=" + destFacId + ", mvmtSchdDepartureDt="
				+ mvmtSchdDepartureDt + ", hasCutoff=" + hasCutoff
				+ ", firstSecDesig=" + firstSecDesig + ", lastSecDesig="
				+ lastSecDesig + ", carrierCode=" + carrierCode
				+ ", networkRouteNum=" + networkRouteNum + ", mvmtEtaDt="
				+ mvmtEtaDt + ", transportationModeCode="
				+ transportationModeCode + ", vehicleId=" + vehicleId
				+ ", mvmtStatusCode=" + mvmtStatusCode + ", oriSvaCode="
				+ oriSvaCode + ", destSvaCode=" + destSvaCode + ", createdBy="
				+ createdBy + ", createdDt=" + createdDt + ", updatedBy="
				+ updatedBy + ", updatedDt=" + updatedDt + ", fleetType="
				+ fleetType + ", mawbId=" + mawbId + ", docTypeCd=" + docTypeCd
				+ ", sysGuid=" + sysGuid + ", closeDt=" + closeDt
				+ ", departDt=" + departDt + ", cutOffTime=" + cutOffTime + "]";
	}
	
}
